server:
  port: 8071


spring:
  application:
    name: RatingService
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:C:\\Users\\H2-Database\\RatingMicroservice
    driverClassName: org.h2.Driver
    username: user
    password: 
  h2:
    console:
      enabled: true
      path: /h2-consoles
