server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USERSERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: http://localhost:8091
          predicates:
            - Path=/hotels/**

        - id: RATINGSERVICE
          uri: http://localhost:8071
          predicates:
            - Path=/ratings/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
